[project]
name = "password-generator"
version = "0.1.0"
description = "CLI Password manager"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argon2-cffi>=25.1.0",
]

[project.scripts]
passgen = "passwordgen.main:main"
